### ISSUE TITLE
Version 0.6.1-3 Chat list doesn't order by latest messages anymore

### ISSUE THREAD

**Issue by Windyk-20** [Wunderfitz/harbour-fernschreiber#302] opened 2021-01-09 16:36 UTC
Since Update to 0.6.1-3 the Chat list on my device (Xperia XA2 Dual Sim) the chat list is no longer sortet by latest messages, whitch is a bit anoying, is this Problem known or exclusive to me.

btw great app and nice constant feature updating

I hope this is the right way to adress this issue.

**Comment by Wunderfitz** [comment] 2021-01-09 17:19
Some people have reported similar issues and it could also be related to #299 and is definitely caused by TDLib 1.7 (there was a major upgrade under the hood). For some unknown reasons there are some inconsistencies between other clients (especially official ones) and TDLib-based clients. All people who have reported that to me so far could successfully solve this problem on their own. Possible approaches are:
- Have Fernschreiber open
- Unpin all chats in another client (pin/unpin chats will be in 0.7)
- Pin the respective chats again
- If not yet solved, open the erroneously sorted chats once and go back to the main screen
- If this still doesn't solve the issue, you can reinitialize the message cache (which is administered by TDLib). Close Fernschreiber and remove the file ~/.local/share/harbour-fernschreiber/harbour-fernschreiber/tdlib/db.sqlite. Afterwards start Fernschreiber again and the list should be created from scratch

**Comment by Windyk-20** [comment] 2021-01-09 17:54
Ok unpin and pin did work... Wierd... But thanks a lot for the quick answer...

On Saturday, 9 January 2021, Sebastian Wolf wrote:
> Some people have reported similar issues and it could also be related to #299 and is definitely caused by TDLib 1.7 (there was a major upgrade under the hood). For some unknown reasons there are some inconsistencies between other clients (especially official ones) and TDLib-based clients. All people who have reported that to me so far could successfully solve this problem on their own. Possible approaches are:
> - Have Fernschreiber open
> - Unpin all chats in another client (pin/unpin chats will be in 0.7)
> - Pin the respective chats again
> - If not yet solved, open the erroneously sorted chats once and go back to the main screen
> - If this still doesn't solve the issue, you can reinitialize the message cache (which is administered by TDLib). Close Fernschreiber and remove the file ~/.local/share/harbour-fernschreiber/harbour-fernschreiber/tdlib/db.sqlite. Afterwards start Fernschreiber again and the list should be created from scratch
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Wunderfitz/harbour-fernschreiber/issues/302#issuecomment-75733804

--

**Comment by Wunderfitz** [comment] 2021-01-09 19:54
Great, thanks for letting me know. Closing this issue then...

**Closed by Wunderfitz** 2021-01-09 19:54 UTC
Labels: bug
