### ISSUE TITLE
Have a share plugin

### ISSUE THREAD

**Issue by legacychimera247** [Wunderfitz/harbour-fernschreiber#509] opened 2022-10-02 00:30 UTC
Hello,
one thing i really miss from the official telegram (or better android per se) is a share option. Sailfish have such a thing via the new menu but very few apps seems to implement that function. Would be very nice and very handy for fernschreiber to have such a plugin :)

**Comment by monich** [comment] 2022-10-02 02:04
There are (at least) two problems with share plugins:
1. They are not allowed in Jolla Store
2. The sharing API is changing like crazy from one Sailfish OS release to another

**Comment by legacychimera247** [comment] 2022-10-02 13:34
I thought they had stabilized everything with the new share ui they implemented...

**Comment by Wunderfitz** [comment] 2022-10-03 17:52
It's just the one way they did it (open the share-with menu), but the integration in this menu is still like @monich mentioned. Need to close this as it's a duplicate of #17

**Closed by Wunderfitz** 2022-10-03 17:52 UTC
Labels: duplicate
